// stopgap boilerplate generated by chatgpt
public class Card {
    private String face; 
    private String suit; 

    // constructor to initialize Card object
    public Card(String face, String suit) {
        this.face = face;
        this.suit = suit;
    }
    // getter methods
    public String getFace() {return face;}
    public String getSuit() {return suit;}

    // string representation of card
    @Override
    public String toString() {
        return face + " of " + suit;
    }
}